// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4949.Trainer.subsystems;

import org.usfirst.frc4949.Trainer.Logging;
import org.usfirst.frc4949.Trainer.RobotMap;
import org.usfirst.frc4949.Trainer.commands.*;

import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.Counter;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drive extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon lrController = RobotMap.drivelrController;
    private final CANTalon rrController = RobotMap.driverrController;
    private final CANTalon rfController = RobotMap.driverfController;
    private final CANTalon lfController = RobotMap.drivelfController;
    private final RobotDrive robotDrive = RobotMap.driveRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final ADXRS450_Gyro spiGyro = RobotMap.driveADXRS450_Gyro;
    private final Counter rfEncoder = RobotMap.driverfEncoder;
    private final Counter rrEncoder = RobotMap.driverrEncoder;
    private final Counter lfEncoder = RobotMap.drivelfEncoder;
    private final Counter lrEncoder = RobotMap.drivelrEncoder;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveWithJoystick());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
	/**
	 * @param joy
	 */
	public void mecanumDrive(Joystick joy) {
		double xAxis = joy.getX();
		double yAxis = joy.getY();
		double zAxis = joy.getZ();
		xAxis = Math.min(xAxis,1);
		xAxis = Math.max(xAxis,-1);
		yAxis = Math.min(yAxis,1);
		yAxis = Math.max(yAxis,-1);
		zAxis = Math.min(zAxis,1);
		zAxis = Math.max(zAxis,-1);
		double angle = 0.0;
		Logging.consoleLog("%s,%d,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f",
				"JOY",
				System.currentTimeMillis(),
				(double) lfEncoder.get(),
				(double) lrEncoder.get(),
				(double) rfEncoder.get(),
				(double) rrEncoder.get(),
				(double) lfEncoder.getDistance(),
				(double) lrEncoder.getDistance(),
				(double) rfEncoder.getDistance(),
				(double) rrEncoder.getDistance(),
				(double) xAxis,
				(double) yAxis,
				(double) zAxis,
				(double) angle,
				(double) spiGyro.getAngle());
		robotDrive.mecanumDrive_Cartesian(xAxis, yAxis, zAxis, angle);
	}

	/**
	 * @param xAxis
	 *            X axis value
	 * @param yAxis
	 *            Y axis value
	 * @param zAxis
	 *            Z axis value
	 */
	public void calculateDrive(double xAxis, double yAxis, double zAxis, double angle) {
		Logging.consoleLog("%s,%d,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f",
				"CMP",
				System.currentTimeMillis(),
				(double) lfEncoder.get(),
				(double) lrEncoder.get(),
				(double) rfEncoder.get(),
				(double) rrEncoder.get(),
				(double) lfEncoder.getDistance(),
				(double) lrEncoder.getDistance(),
				(double) rfEncoder.getDistance(),
				(double) rrEncoder.getDistance(),
				(double) xAxis,
				(double) yAxis,
				(double) zAxis,
				(double) angle,
				(double) spiGyro.getAngle());
		robotDrive.mecanumDrive_Cartesian(xAxis, yAxis, zAxis, angle);
	}
	/**
	 * @param xAxis
	 *            X axis value
	 * @param yAxis
	 *            Y axis value
	 * @param zAxis
	 *            Z axis value
	 */
	public void simulateDrive(double xAxis, double yAxis, double zAxis, double angle) {
		Logging.consoleLog("%s,%d,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f",
				"SIM",
				System.currentTimeMillis(),
				(double) lfEncoder.get(),
				(double) lrEncoder.get(),
				(double) rfEncoder.get(),
				(double) rrEncoder.get(),
				(double) lfEncoder.getDistance(),
				(double) lrEncoder.getDistance(),
				(double) rfEncoder.getDistance(),
				(double) rrEncoder.getDistance(),
				(double) xAxis,
				(double) yAxis,
				(double) zAxis,
				(double) angle,
				(double) spiGyro.getAngle());
	}

	/**
	 * Stop the drive from moving.
	 */
	public void stop() {
		robotDrive.mecanumDrive_Cartesian(0, 0, 0, 0);
	}

	/**
	 * @return The encoder getting the distance and speed of left front of the
	 *         drive.
	 */
	public Counter getLeftFrontEncoder() {
		return lfEncoder;
	}

	/**
	 * @return The encoder getting the distance and speed of left rear of the
	 *         drive.
	 */
	public Counter getLeftRearEncoder() {
		return lrEncoder;
	}

	/**
	 * @return The encoder getting the distance and speed of right front of the
	 *         drive.
	 */
	public Counter getRightFrontEncoder() {
		return rfEncoder;
	}
	
	/**
	 * @return The encoder getting the distance and speed of right rear of the
	 *         drive.
	 */
	public Counter getRightRearEncoder() {
		return rrEncoder;
	}

	/**
	 * @return The current angle of the drive.
	 */
	public double getAngle() {
		return spiGyro.getAngle();
	}
	
}
