// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4949.Trainer.commands;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc4949.Trainer.Logging;
import org.usfirst.frc4949.Trainer.Robot;

/**
 *
 */
public class DriveWithGyro extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double m_Distance;
    private double m_Speed;
    private double m_Bearing;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	private double driveSpeed;
	private double distance;
	private double distanceMoved;
	private long startTimeMillis;
	private long currentTimeMillis;
	private double error;
	private double angle;
	private double course;
	private double xAxis;
	private double yAxis;
	private double zAxis;
	private final double kP = 1.0;
	private final double kPivot = 0.03;
	private final double kSpeedConv = 0.25;
	
	public DriveWithGyro() {
		this(10, 0.5);
	}

	public DriveWithGyro(double dist) {
		this(dist, 0.5);
	}

	public DriveWithGyro(double dist, double vel) {
		this(dist, vel, 0.0);
	}


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveWithGyro(double Distance, double Speed, double Bearing) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_Distance = Distance;
        m_Speed = Speed;
        m_Bearing = Bearing;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Logging.consoleLog("Starting to Drive With Gyro.");
    	error = m_Distance;
    	
    	startTimeMillis = System.currentTimeMillis();
		setTimeout(2);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	driveSpeed = m_Speed;
    	course = Robot.drive.getAngle();
        angle = course - m_Bearing;  // get current heading deviation

    	if (Robot.hasEncoders) {
    		error = (distance - Robot.drive.getRightFrontEncoder().getDistance());
    	} else {
        	currentTimeMillis = System.currentTimeMillis();
        	distanceMoved = (currentTimeMillis - startTimeMillis) * driveSpeed * kSpeedConv;
    		error = distance - distanceMoved;
    	}
    	
        xAxis = 0;                       // push drive to target line, if known
        yAxis = driveSpeed * kP;         // push drive towards target
        zAxis = -angle * kPivot;         // push drive towards heading 0
        
		if (error >= 0) {
			xAxis = Math.min(xAxis,1);
			xAxis = Math.max(xAxis,-1);
			yAxis = Math.min(yAxis,1);
			yAxis = Math.max(yAxis,-1);
			zAxis = Math.min(zAxis,1);
			zAxis = Math.max(zAxis,-1);
			// Robot.drive.simulateDrive(xAxis, yAxis, zAxis, 0);
			Robot.drive.calculateDrive( xAxis, yAxis, zAxis, 0.0);
		}		
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	if (error <= 0) {
    		return true;
    	}
    	else {
    		return false;
    	}
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drive.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
